#!/usr/bin/env node
/**
 * **The roadmap, derived.**
 *
 *   node scripts/roadmap.ts           # write docs/ROADMAP.md
 *   node scripts/roadmap.ts --check   # fail if it is out of date, for CI
 *
 * Status lives in each phase's own front matter, where it cannot drift from
 * the thing it describes. This reads it. `docs/ROADMAP.md` is generated and
 * says so at the top; editing it by hand is editing the wrong file.
 *
 * Ported from dalmaer/ledger, which ported it from isocan, for the same
 * reason both times: status kept in more than one hand-written place ends up
 * disagreeing with itself, and nothing can tell which copy is older.
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export const STATUSES = ["planned", "designed", "partial", "built", "lived-in", "superseded"] as const;
export type Status = (typeof STATUSES)[number];

const REPO = "dalmaer/duo";
const ROOT = join(import.meta.dirname, "..");
const PHASES_DIR = join(ROOT, "docs", "phases");
const OUT = join(ROOT, "docs", "ROADMAP.md");

const HEADER =
  "<!-- Generated by scripts/roadmap.ts. Do not edit — edit the front matter\n     of the phase itself, which is where its status lives. -->";

/** Reading order: settled first, then what is moving, then what is not. */
const ORDER: Status[] = ["lived-in", "built", "partial", "designed", "planned", "superseded"];
const HEADING: Record<Status, string> = {
  "lived-in": "Lived in",
  built: "Built, not yet lived in",
  partial: "Partly built",
  designed: "Designed",
  planned: "Not started",
  superseded: "Superseded",
};

export interface Meta {
  status: Status | null;
  since: string | null;
  issue: number | null;
  note: string | null;
}

/**
 * Front matter, as far as a phase uses it: flat `key: value` lines, values
 * optionally quoted. Anything richer belongs in the body.
 */
export function frontMatter(raw: string): Record<string, string | number> {
  const m = raw.match(/^---\n([\s\S]*?)\n---/);
  const out: Record<string, string | number> = {};
  if (!m) return out;
  for (const line of m[1]!.split("\n")) {
    const kv = line.match(/^([a-z_]+):\s*(.*?)\s*(#.*)?$/);
    if (!kv) continue;
    let v = kv[2]!;
    if (/^".*"$/.test(v)) v = JSON.parse(v) as string;
    else if (/^'.*'$/.test(v)) v = v.slice(1, -1);
    out[kv[1]!] = /^\d+$/.test(v) ? Number(v) : v;
  }
  return out;
}

export function metaOf(raw: string): Meta {
  const d = frontMatter(raw);
  return {
    status: (STATUSES as readonly unknown[]).includes(d.status) ? (d.status as Status) : null,
    since: typeof d.since === "string" && /^\d{4}-\d{2}-\d{2}$/.test(d.since) ? d.since : null,
    issue: typeof d.issue === "number" ? d.issue : null,
    note: typeof d.note === "string" && d.note.trim() ? d.note.trim() : null,
  };
}

/** What is wrong with a phase's status block, in words meant to be read. */
export function problems(meta: Meta, raw: string): string[] {
  const out: string[] = [];
  if (!meta.status) out.push(`no status — add one of: ${STATUSES.join(", ")}`);
  if (!meta.since) out.push("no since — the date it entered this status, as YYYY-MM-DD");
  if (!meta.note) out.push("no note — one line on why it stands where it does");
  if (!/\*\*Done when\.?\*\*/.test(raw)) out.push("no **Done when** — name the testable outcome before starting");
  return out;
}

export function isPhaseFile(name: string): boolean {
  return name.endsWith(".md") && name !== "README.md";
}

interface Phase {
  file: string;
  title: string;
  n: number;
  meta: Meta;
  problems: string[];
}

async function collect(): Promise<Phase[]> {
  const names = (await readdir(PHASES_DIR)).filter(isPhaseFile);
  const out: Phase[] = [];
  for (const file of names) {
    const raw = await readFile(join(PHASES_DIR, file), "utf8");
    const meta = metaOf(raw);
    out.push({
      file,
      title: raw.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? "untitled",
      n: Number(file.split("-")[0]),
      meta,
      problems: problems(meta, raw),
    });
  }
  // By number, not filename, so 10 does not sort before 2.
  return out.sort((a, b) => a.n - b.n);
}

export function render(phases: Phase[]): string {
  const by = new Map<Status, Phase[]>();
  for (const p of phases) if (p.meta.status) by.set(p.meta.status, [...(by.get(p.meta.status) ?? []), p]);
  const lived = phases.filter((p) => p.meta.status === "lived-in").length;
  const out = [
    HEADER,
    "# Roadmap",
    "",
    "Every phase, by where it stands. **Derived**: the status of a phase lives",
    "in that phase's own front matter, so it cannot drift from what it",
    "describes. Run `npm run roadmap` after changing one.",
    "",
    `**${lived} of ${phases.length} phases lived in.** *Lived in* is a judgement, not a`,
    "date: people have used the thing and it held. *Built* is the weaker claim —",
    "the code exists and has been run.",
    "",
  ];
  for (const status of ORDER) {
    const group = by.get(status);
    if (!group?.length) continue;
    out.push(`## ${HEADING[status]} <sub>${group.length}</sub>`, "", "| | Phase | Since | |", "| --- | --- | --- | --- |");
    for (const p of group) {
      const issue = p.meta.issue ? ` · [#${p.meta.issue}](https://github.com/${REPO}/issues/${p.meta.issue})` : "";
      out.push(`| ${p.n} | [${p.title}](phases/${p.file}) | ${p.meta.since ?? "—"} | ${p.meta.note ?? "—"}${issue} |`);
    }
    out.push("");
  }
  const broken = phases.filter((p) => p.problems.length);
  if (broken.length) {
    out.push("## Needs a verdict", "");
    for (const p of broken) out.push(`- [\`${p.file}\`](phases/${p.file}) — ${p.problems.join("; ")}`);
    out.push("");
  }
  return out.join("\n");
}

if (import.meta.main) {
  const phases = await collect();
  const page = render(phases);
  if (process.argv.includes("--check")) {
    const current = await readFile(OUT, "utf8").catch(() => "");
    if (current.trim() !== page.trim()) {
      console.error("docs/ROADMAP.md is out of date — run: npm run roadmap");
      process.exit(1);
    }
    const broken = phases.filter((p) => p.problems.length);
    if (broken.length) {
      for (const p of broken) console.error(`docs/phases/${p.file}: ${p.problems.join("; ")}`);
      process.exit(1);
    }
    console.log(`docs/ROADMAP.md is current — ${phases.length} phases, all with a verdict`);
  } else {
    await writeFile(OUT, page + "\n", "utf8");
    console.log(`wrote docs/ROADMAP.md — ${phases.length} phases`);
  }
}
